/* Generated by Together */

package com.miw.model;


import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
public class Buy {
	
	
	@Id @GeneratedValue
	private int id;
	private double price;
	private String estado;
	private String direccion;
	@JoinColumn(name = "user", nullable = false)
    @ManyToOne(optional = false, cascade = CascadeType.MERGE, fetch = FetchType.EAGER)
	private User user;
	


	public double getPrice() {
		return price;
	}

	
	public Buy() {
		super();
		// TODO Auto-generated constructor stub
	}


	public Buy(double price, String estado, String direccion, User user) {
		super();
		this.price = price;
		this.estado = estado;
		this.direccion = direccion;
		this.user = user;
	}
	
	

	public User getUser() {
		return user;
	}


	public void setUser(User user) {
		this.user = user;
	}


	public void setPrice(double price) {
		this.price = price;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	

	@Override
	public String toString() {
		return "Buy [id=" + id + ", direccion=" + direccion + ", estado=" + estado + ", user=" + user.getId()
				+ ", price=" + price + "]";
	}

}
