/* Generated by Together */

package com.miw.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class User {
	
	
	@Id @GeneratedValue
	private int id;
	private String username;
	private String password;
	private Boolean admin;
	

	

	
	public User() {
		super();
		// TODO Auto-generated constructor stub
	}


	public User(String username, String password, Boolean admin) {
		super();
		this.username = username;
		this.password = password;
		this.admin = admin;
	}
	


	public void setUsername(String username) {
		this.username = username;
	}

	public String getUsername() {
		return username;
	}
	public void setPassword(String password) {
		this.password = password;
	}

	public String getPassword() {
		return password;
	}

	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}

	public Boolean getAdmin() {
		return admin;
	}


	public void setId(int id) {
		this.id = id;
	}
	public int getId() {
		return id;
	}
	

	@Override
	public String toString() {
		return "User [id=" + id + ", username=" + username + ", password=" + password + ", admin=" + admin+ "]";
	}
}
